linux_task:
  container:
    image: ubuntu:latest
    cpu: 2
    memory: 8G

  env:
    VCPKG_FORCE_SYSTEM_BINARIES: 1

  install_script:
    - apt-get update
    - apt-get install -y cmake ninja-build zip unzip curl git aria2 python3 g\+\+

  submodules_script:
    - git submodule update --init --recursive

  vcpkg_cache:
    folder: _build-release-x64-gcc/vcpkg_installed
    fingerprint_script:
      - cat vcpkg.json

  build_script:
    - cmake --preset lnx-gcc-x64-rel -S. || cat vcpkg/buildtrees/llvm/install-x64-linux-rel-out.log
    - cmake --build --preset rel-full-rebuild-lnx-gcc

windows_task:
  container:
    image:
