alpine_task:
  container:
    image: alpine:latest

  install_script:
    - apk add build-base cmake ninja zip unzip curl git

  submodules_script:
    - git submodule update --init --recursive

  vcpkg_cache:
    folder: _build-release-x64-gcc/vcpkg_installed
    fingerprint_script:
      - cat vcpkg.json

  build_script:
    - cmake --preset lnx-gcc-x64-rel -S. || cat _build-release-x64-gcc/vcpkg-bootstrap.log
    - cmake --build --preset rel-full-rebuild-lnx-gcc
