linux_task:
  container:
    image: gcc:latest
    cpu: 8
    memory: 32G

  env:
    PATH: /tmp/cirrus-ci-build/cmake-3.25.1-linux-x86_64/bin:${PATH}

  install_script:
    - apt-get update
    - apt-get install -y curl ninja-build zip unzip curl git aria2 python3 g\+\+
    - curl -L https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.tar.gz -o cmake-install.tar.gz
    - tar xzf cmake-install.tar.gz

  submodules_script:
    - git submodule update --init --recursive

  vcpkg_cache:
    folder: vcpkg/packages
    fingerprint_script:
      - cat vcpkg.json

  build_script:
    - cmake --preset lnx-gcc-x64-rel -S. || cat vcpkg/buildtrees/llvm/install-x64-linux-rel-out.log
    - cmake --build --preset rel-full-rebuild-lnx-gcc

  src_package_script:
    - cmake --build _build-release-x64-gcc --target package_source

  package_script:
    - cmake --build _build-release-x64-gcc --target package

  source_artifacts:
    path: _build-release-x64-gcc/cg3-*-Source.tar.xz

  binary_artifacts:
    path: _build-release-x64-gcc/*.deb
