= cg3
:icons: font

image:https://badgen.net/github/checks/bodand/cg3/trunk/windows_test?label=Windows x86_64/MSVC[]
image:https://badgen.net/github/checks/bodand/cg3/trunk/linux_test?label=Linux x86_64/GCC[]
image:https://badgen.net/github/checks/bodand/cg3/trunk/linux_arm_test?label=Linux ARM64/GCC[]

Prog1 nagy házi sanity-check framework.

A clang AST-t felhasználva ellenőrzéseket hajt végre, a különböző követelmények teljesítésére.
Ezek fordítási időben eldönthetőek, hogy melyiket fordítjuk bele a programba.

== Ellenőrzések

A mindenkori verzióban elérhető ellenőrzések a `checks/` mappában találhatóak meg.
Ezekhez a részletesebb leírás a saját mappájuk README fájljában látható.

== Installation

=== GitHub Release

GitHub Release-ben elérhetőek bináris csomagok különböző féle-fajta operációs rendszerekre és processzor architektúrákra.
Ezek egyszerűen telepíthetőek, és nem igényelnek egyéb műveletet.

=== GitHub

==== Bleeding edge

Jelenleg cg3 forrása elérhető GitHubról, és ezáltal következő parancssal letölthető:

[source,shell]
----
$ git clone --recursive https://github.com/bodand/cg3
----

A projekt fordításához a <<_building>> részben leírtakat érdemes átolvasni.

==== Release sources

Release forráscsomag elérhetőek szintén a különböző releasekhez.
Ezek fordítása várhatólag azonos a legfrissebb fejlesztői verzió fordításával, azaz a <<_building>> részben tárgyaltakkal, de pontos információkért a letöltött csomag README.adoc fájljával kell konzultálni.

NOTE: Bár elég fontosnak tartom, hogy minden projekt a triviális fordítási lépésekkel lefordítható legyen, akár ha ez esetenként jóval elbonyolíthatja a CMake szkripteket, nem tudom garantálni, hogy a különböző verziók pontosan ugyan azzak az inkarncáióval fordulnak.
Ezért érdemes, mindig megnézni a README.adoc fájlt, hátha van benne valami hasznos információ.

[#_building]
== Building

Az egész projektnek egyben kellene fordulna as-is, CMake, vcpkg által támogatott rendszereket, és ahol LLVM is lefordul.

Mivel a projekt fordít magának egy LLVM-et és egy Clang-ot, így az első fordítást érdemes olyankor indítani, amikor nem lenne sok szükség a gépünkre.
A tényleges függőségek a `vcpkg.json` fájlban találhatóak, és vcpkg manifest módját használva automatikusan telepítésre kerülnek.
Jelenleg a telepíthető csomagok készítéséhez szükséges tooling nem tudja biztosítani a megfelelő működést rendszerben talált csomagok esetén, így nem lehet előre buildelt használni a buildhez.
Ennek megoldása folyamatban van.

Ezek ismeretében triviálisan fordítható a következő parancsokkal:

[source,shell]
----
$ cmake -S. -B_build -DCMAKE_BUILD_TYPE=Release
$ cmake --build _build
----

.Ha valaki a teszteket is lekívánja futtatni
Alapból a tesztek között lefut egy _n_ darabra szétvágott lint folyamat, avagy clang-tidy.
Mivel igen sok ellenőrzést kapcsoltunk be, illetve közepesnek mondható a projekt mérete, ezért igen sokáig fog futni ez a feladat.
Amennyiben nem érdekelt valaki, hogy sikeresek-e ezek a tesztek, csak a tényleges kódot kívánja tesztelni, hogy minden megfelelően működik-e a rendszerén a `ctest(1)` híváshoz a `-E clang-tidy` opciót adja hozzá.
Ezzel a clang-tidy tesztek nem fognak lefutni.

WARNING: Ha valaki mégis a lint folyamatot is le szeretné futtatni, érdemes a `-j` opciót használni parallel futtatáshoz.
Így is közel bele lehet 2 órába gyengébb gépeken, nyilván 100%-on használt processzor mellett.
(Intel i7 8750H 6 mag/12 szálas laptopon `-j6` mellett a v0.2.2 vel ekvivalens projekt állapot volt 1 óra 43 perc.)

Telepíteni lehetséges a következő parancssal:

[source,shell]
----
$ cmake --install _build
----

Előre fordított csomagok készítése folyamatban van.

== Contributing

Nem nagyon igényel külön felszereltséget, mint, ha csak saját magának buildelné valaki a projektet.
Amire mindenképp szükség van az up-to-date C++ fordító és CMake 3.22+.

Emellett dokumentáció fordítására Asciidoc (Ruby gem-ként telepíthető), illetve Windowson pandoc.

Mindezek mellett, erősen ajánlott Perl, és a git hookok bekapcsolása (hooks/install.pl).
Utóbbit CMake megcsinálja, amennyiben talál egy `perl`/`perl.exe`-t amivel le tudja futtatni.
Ezek formai ellenőrzéseket fognak végrehajtani commitnál, amit CI is ellenőriz, úgyhogy egyszerűbb lokálisan bajlódni velük, mint soronként patchelni CI-on (utóbbi nem egy kellemes művelet, nem tudom ajánlani.)

[WARNING]
Megjegyzendő, hogy a nekünk szükséges LLVM komponensek debug build Windows/MSVC konfigurációban ~200GB a sok debug szimbólum miatt.
Ugyan emiatt **sokáig** is tart az első build, illetve minden olyan, ami miatt vcpkg azt hiszi, újra kell buildelnie mindent.
Óvatosan `vcpkg.json`-al, a `vcpkg` submodullal, és a build directorykkal.

