= cg3

Prog1 nagy házi sanity-check framework.

A clang AST-t felhasználva ellenőrzéseket hajt végre, a különböző követelmények teljesítésére.
Ezek fordítási időben eldönthetőek, hogy melyiket fordítjuk bele a programba.

== Ellenőrzések

A mindenkori verzióban elérhető ellenőrzések a `checks/` mappában találhatóak meg.
Ezekhez a részletesebb leírás a saját mappájuk README fájljában látható.

Jelenleg támogatott ellenőrzések:

bugmalloc::
Ellenőrzi, hogy létezik-e olyan allokációs függvényhívás, amelyik nem halad keresztül a `debugmalloc.h` fájl makróin.

globus::
Megkeresi, vagy legalább megpróbálja, a globális változókat a projektben.

fio::
Keres fájlkezelésre utaló nyomokat.
Elvileg képes elkapni a cselesebb platformspecifikus függvényeket is, ha valaki megpróbálna ilyet csinálni.

== Installation

=== GitHub

Jelenleg cg3 forrása elérhető GitHubról, és ezáltal következő parancssal letölthető:

[source,shell]
----
$ git clone --recursive https://github.com/bodand/cg3
----

A projekt fordításához a <<_building>> részben leírtakat érdemes átolvasni.

== Building

Az egész projektnek egyben kellene fordulna as-is, CMake, vcpkg által támogatott rendszereket, és ahol LLVM is lefordul.

Mivel a projekt fordít magának egy LLVM-et és egy Clang-ot, így az első fordítást érdemes olyankor indítani, amikor nem lenne sok szükség a gépünkre.
A tényleges függőségek a `dependencies.txt` fájlban találhatóak.
Jelenleg a telepíthető csomagok készítéséhez szükséges tooling nem tudja biztosítani a megfelelő működést rendszerben talált csomagok esetén, így nem lehet előre buildelt használni a buildhez.
Ennek megoldása folyamatban van.

Ezek ismeretében triviálisan fordítható a következő parancsokkal:

[source,shell]
----
$ cmake -S. -B_build -DCMAKE_BUILD_TYPE=Release
$ cmake --build _build
----

Telepíteni lehetséges a következő parancssal:

[source,shell]
----
$ cmake --install _build
----

Előre fordított csomagok készítése folyamatban van.

