=== cg3 db (cg3-db(1))

Generates compilation database for trivially compilable projects.

== OPTIONS

-?, -h, --help::
Shows a short help message about available options and parameterization then exits with exit code 1.

-R, --recurse::
Recurses into the given directory, for up-to four directory layers.
If not provided cg3-db will only search for sources in the exactly given directory.

-d _<depth>_, --max-depth=_<depth>_::
Limits recursion to a maximum depth.
By default recursion is only until 4 directories, but this option can set it to either lower or higher.
Its value is ignore if *-R* is not specified, and _depth_ 0 is equivalent to not recursing.

-p _<filter>_, --path-filter=_<filter>_::
Sets a path filter on the searched files.
A path filter is used to filter out files based on their entire path.
For example the bath filter `build` will exclude all files whose path contains the substring `build`.

-f _<filter>_, --file-filter=_<filter>_::
Sets a file filter on the searched files.
A file filter is used to filter purely on filenames.
If a filename contains _filter_, then it will be excluded.

-O _<option>_, --option=_<option>_::
Adds an option to be passed through to the compiler in the generated compilation database.
This is not checked for validity against the used compiler, just written to the JSON file as-is.

-G, --gcc::
Behave as if gcc was the compiler used.
Relevant for the compilation flags generated.

-M, --cl::
Behave as if CL.EXE was the compiler used.
Relevant for the compilation flags generated.
