= cg3(1)
András Bodor <bodand@proton.me>
v0.2.1
:doctype: manpage

== NAME

cg3 - Central driver for the executables in the cg3 suite

== SYNOPSIS

*cg3* check [CHECK] [-dfhMpR] [<directory> | <sources>...] +
*cg3* db [-dfGhMOpR] <compiler> +
*cg3* --help +
*cg3* --version +

== OPTIONS

-h, --help:: Prints help and exits.

-v, --version:: Prints version of cg3 and exits.

== DESCRIPTION

The *cg3* executable is a general driver for the list of executables in the cg3-checker package.

Most commands are implemented as separate executables, which are called from this executable with different arguments specified to the command.
For different options available for the commands, see their respective manuals.

Brief overview of commands follows, this describes what the command does, along with the main manual page, which can be consulted for detailed information.

All options not listed are passed as-is to the called subprocess implementing the command.

include::cg3/cmd-check.adoc[]

include::cg3/cmd-db.adoc[]

== SEE ALSO

cg3-check(1), cg3-db(1)
